# Generated by Django 6.0 on 2026-02-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google', 'Google'), ('isbndb', 'ISBNdb')], max_length=20)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('thumbnail_url', models.URLField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_book_source_external')],
            },
        ),
    ]
