# Generated by Django 6.0 on 2026-02-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
