# Generated by Django 6.0 on 2026-01-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='default-profile.png', upload_to='profile_pics')),
                ('blurb', models.TextField(blank=True, max_length=140)),
                ('about_me', models.TextField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('favorite_genre', models.CharField(blank=True, max_length=100)),
                ('favorite_author', models.CharField(blank=True, max_length=100)),
                ('recommend_to_everyone', models.CharField(blank=True, max_length=100)),
                ('currently_reading', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
