# Generated by Django 6.0 on 2025-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_remove_profile_display_name_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pics'),
        ),
    ]
