# Generated by Django 6.0 on 2025-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_profile_about_me_profile_currently_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics'),
        ),
    ]
