# Generated by Django 6.0 on 2025-12-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blurb',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
