# Generated by Django 6.0 on 2025-12-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_profile_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blurb',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
