# Generated by Django 6.0 on 2026-01-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0010_alter_profile_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
