# Generated by Django 6.0 on 2026-02-08 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('shelves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('have_read', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='shelf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_shelf_name_per_user'),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelves.shelf'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='user_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.userbook'),
        ),
        migrations.AddConstraint(
            model_name='userbook',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='uniq_user_book'),
        ),
        migrations.AddConstraint(
            model_name='shelfitem',
            constraint=models.UniqueConstraint(fields=('shelf', 'user_book'), name='uniq_book_per_shelf'),
        ),
    ]
