# Generated by Django 6.0 on 2026-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_shelfitem_userbook_shelf_description_shelf_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
