# Generated by Django 6.0 on 2026-02-09 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_shelf_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
