# Generated by Django 6.0 on 2026-02-15 19:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_shelf_created_at_shelf_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='uniq_shelf_user_slug'),
        ),
    ]
