# Generated by Django 6.0 on 2026-02-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_shelf_slug_shelf_uniq_shelf_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
