# Generated by Django 6.0 on 2026-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_userbook_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
