# Generated by Django 6.0 on 2026-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_backfill_shelfitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfitem',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
